# Generated by Django 3.0.8 on 2020-07-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Todos',
        ),
    ]
